### PR TITLE
Update list of domains

### PR DESCRIPTION
**Pull request by dverma1232**

### CODE REVIEW

**Review by daylamtayari — APPROVED** [review]
Thank you, adding

**Comment by dverma1232** [comment]
@daylamtayari I just noticed the new domains have a / at the end, would that be an issue?

**Comment by daylamtayari** [comment]
Good point, I dont believe so but let me double check
iirc I still passed it through a regex filter before using it

**Comment by daylamtayari** [comment]
I didn't, Ill remove the slashes out of precaution

**Pull request merged**
